version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    ports:
    - 7474:7474
    - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment: 
      # Disable auth for now
      - NEO4J_dbms_security_auth__enabled=false

      